# 当前为GitHub Actions 的 YAML 文件，GitHub 检测到仓库有 push/PR 时就自动执行里面的步骤。

name: 测试          # 流水线名称，GitHub 页面上显示

on:                # 什么时候触发
  push:
    branches: [main]      # main 分支有推送就触发
  pull_request:
    branches: [main]      # 有人提 PR（pre request） 到 main 也触发

jobs:          # 干什么活
  test:        # 第一个任务叫 test（随便起）
    runs-on: ubuntu-latest  # 在 GitHub 提供的 Ubuntu 虚拟机上跑
    strategy:
      matrix:    # matrix 多版本策略—— 同一套测试，让 GitHub 同时在 Python 3.12 和 3.13 上各跑一遍。两个版本分别起一个 CI
        python-version: ['3.12', '3.13']
    steps:     # 任务分几步
      - uses: actions/checkout@v4        # 步骤1：拉代码 。@v4:2负责拉代码的脚本，目前迭代到第 4 版（官方维护，最新且最稳定的大版本自动化脚本）
      - uses: actions/setup-python@v5    # 步骤2：装 Python。 @v5:负责装 Python 的脚本，目前迭代到第 5 版（官方维护，最新且最稳定的大版本自动化脚本）
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt   # 步骤3：装依赖
      - run: pytest tests/ -v --ignore-glob=tests/test_ui_*.py   # 步骤4：跑测试（指定目录），并忽略部分用例（因 Dockerfile 中配置了装了slim 版的 python，没有浏览器，故无法执行 UI测试，这里跳过了）
